language: clojure
jdk:
  - oraclejdk8
addons:
      postgresql: "9.3"
before_script:
      - psql -c 'create database qlma;' -U postgres
      - echo 'db.host="localhost"' >> app.properties
      - echo 'db.user="postgres"' >> app.properties
      - echo 'db.password=""' >> app.properties
      - echo 'db.db="qlma"' >> app.properties

